GVK Fixes for railgun POC
Kong/kubernetes-ingress-controller pull request #1045
Opened 2021-02-23 20:08 UTC by shaneutt

I noticed some typographical errors for GVK's for our native types from the POC and this PR resolves those.

2021-02-23 21:51 UTC, rainest commented
Do we indeed want to use this new group and version? While the `.my.domain` part is definitely wrong, we currently have the `configuration.konghq.com` group and use v1 for our CRDs, e.g.

https://github.com/Kong/kubernetes-ingress-controller/blob/v1.1.1/deploy/manifests/base/custom-types.yaml#L4-L8

```
metadata:
  name: kongplugins.configuration.konghq.com
spec:
  group: configuration.konghq.com
  version: v1
```
I'd think we'd want to preserve that at least initially so that users don't need to migrate their resources, correct? As far as I know, we're not planning to make breaking changes to definitions that'd warrant a GVK change.

2021-02-24 13:07 UTC, shaneutt commented
> configuration

The `networking` group was an intentional change, but now that you've mentioned it and given the evolving goals of this project I think the caution you're suggesting makes sense. We can hold back on this change for now and I'll create a follow up issue to re-address it at a later time.

2021-02-24 13:30 UTC, shaneutt commented
@rainest the changes back to `configuration.konghq.com` are up now, ready for re-review :vulcan_salute:

2021-02-24 20:29 UTC, rainest requested changes
Will still need to preserve version `v1` instead of `v1beta1` as well.

2021-02-24 23:05 UTC, mflendrich reviewed
For each of the CRDs, please ensure that:
- the API version (v1/v1beta1) matches https://github.com/Kong/kubernetes-ingress-controller/tree/main/pkg/apis/configuration
- the CRDs generated here are identical to those in https://github.com/Kong/kubernetes-ingress-controller/blob/main/deploy/manifests/base/custom-types.yaml . This will be important when we get our users to update.

2021-02-25 13:39 UTC, shaneutt commented
ready for re-review, however on this issue:

> the CRDs generated here are identical

I skipped on worrying about this for now as we're still not 100% ready to fix our generators yet, and this is definitely something we should discuss in the upcoming spike.

2021-02-25 14:51 UTC, mflendrich approved these changes

2021-02-25 14:52 UTC, mflendrich commented
> and this is definitely something we should discuss in the upcoming spike.

Before merging, please record this in #1043.

2021-02-25 16:56 UTC, rainest approved these changes

2021-02-25 17:30 UTC, merged