fix serviceName when backend.service.port uses name instead of number
Kong/kubernetes-ingress-controller pull request #1177
Opened 2021-04-12 02:22 UTC by ianhe8x

**What this PR does / why we need it**:
For IngressV1beta1 the servicename in kong is composed of `ingress.Namespace`.`Backend.ServiceName`.`Backend.ServicePort.String()`
if servicePort is represented as string name, it will use the string name. otherwise it will use the port number.

But for IngressV1, `Backend.Service.Port.Number` is used. It causes an issue when I have both http and ws in the ingress and they use different ports (defined by string name). Only one kong service will be created, the last part of service name is `".0" `

**Special notes for your reviewer**:
I'm not sure where is the most preferred place to put `func serviceBackendPortToStr` pls advice then I will make change.

2021-04-12 02:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Kong/kubernetes-ingress-controller?pullRequest=1177) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Kong/kubernetes-ingress-controller?pullRequest=1177) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Kong/kubernetes-ingress-controller?pullRequest=1177) it.</sub>

2021-04-12 10:13 UTC, mflendrich requested changes
Thank you for this contribution. The problem stated exists indeed, but the proposed solution can potentially generate non-unique names in a corner case where the port name is a string representing a number (e.g. `name: "80"`). 

Please make the added function a little more defensive by qualifying the generated name with a prefix depending on the source of generation. An example solution attached in a comment below. Also, please add a unit test. Otherwise the change looks fine :+1:.

2021-04-12 10:13 UTC, mflendrich commented on pkg/parser/translate.go
> +	return strconv.Itoa(int(port.Number))
```suggestion
	if port.Name != "" {
		return fmt.Sprintf("pname-%s", port.Name)
	}
	return fmt.Sprintf("pnum-%d", port.Number)
```

2021-04-14 03:50 UTC, ianhe8x commented
Hi, I don't know why integration tests failed. It timeouted on master when I run it locally.

2021-04-20 16:07 UTC, mflendrich commented
Thanks @ianhe8x,

Please target `next` with your PR as this is a change that has too much impact to go into a patch release.

> I don't know why integration tests failed
The git checkout error looks like a GitHub Actions machinery/misconfiguration issue that we haven't seen on other PRs - please change PR base (this will probably require rebasing) and let's see if the error still persists.

2021-04-25 10:15 UTC, ianhe8x commented
closes in favour of #1245

2021-04-25 10:15 UTC, closed without merging