fix: deduplicate consumer credential secret keys
Kong/kubernetes-ingress-controller pull request #1670
Opened 2021-08-05 21:18 UTC by shaneutt

**What this PR does / why we need it**:

Any `KongConsumer` resource which includes credentials secrets with a duplicate Key will not be able to properly configure (and will halt all configuration to Kong until it's fixed) currently. This is a stopgap short of future fixes to validation to change this failure from a hard error to a soft error.

**Which issue this PR fixes**

Resolves https://github.com/Kong/kubernetes-ingress-controller/issues/729

**PR Readiness Checklist**:

- [ ] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

2021-08-05 22:44 UTC, rainest requested changes
The restriction here is fairly complex in relation to the K8S data type. The credential Secrets are just generic k/v pairs, but they represent multiple Kong entities with their own distinct schemas.

The actual restriction here is that no two credentials of the same type can have the same unique fields. Those fields are defined per credential type, so to handle this properly, you need something like [these per-credential validators](https://github.com/Kong/kubernetes-ingress-controller/blob/main/internal/kongstate/credentials.go#L48-L149), i.e. check the `kongCredType`, determine the unique fields for that specific type, and check those only against existing credentials of that type. You can't check the keys alone since some can have the same value:

- `kongCredType` can appear multiple times for consumers that have multiple credentials. It can even have the same value multiple times for consumers that have multiple credentials of the same type, which is valid configuration.
- Other keys can appear multiple times with the same value, e.g. you can have multiple JWT credentials with [the same algorithm](https://github.com/Kong/kong/blob/51848a072ebfae24d94b92c824363eefca1c84ee/kong/plugins/jwt/daos.lua#L29-L42)
- Unique keys can appear multiple times as long as their values are different. You can have multiple basic-auth credentials as long as they have [different username values](https://github.com/Kong/kong/blob/51848a072ebfae24d94b92c824363eefca1c84ee/kong/plugins/basic-auth/daos.lua#L19).

This check actually needs to happen across _all_ credentials of a given type--it doesn't actually matter if you've added colliding credentials to the same KongConsumer or not as presented in the issue. You can perform a "if same type, if unique key, if previously-observed value" check in this loop to catch a minority of these cases, but not all.

To elaborate on some of my chat comments earlier, an alternate approach that does validate across all entities would be to use decK's state manager, which provides a limited schema system with the ability to at least check for [unique values in a given column](https://github.com/Kong/deck/blob/c487b5d1fce2451cea65dd70b83d97442691c383/state/consumer.go#L24). At present though, it doesn't actually check credential field uniqueness, only names and IDs for most resources. If we were to use the `Add()`s (and expand the schema checks) in that it'd allow for incremental updates across all resources. That'd be a _massive_ refactor of the controller though.

2021-08-06 17:41 UTC, ccfishk commented on internal/kongstate/kongstate.go
> +							invalid = true
```suggestion
							invalid = true
							break
```
break since find break

2021-08-06 18:30 UTC, closed without merging

2021-08-06 18:39 UTC, mflendrich commented
@shaneutt could you please change the target branch to `main` and reopen this PR? Only the author can do it.

2021-08-06 19:03 UTC, shaneutt commented
This was still just in draft, so no worries I'll just re-open it in a bit once I get more of the work complete :+1:

2021-08-06 20:27 UTC, shaneutt commented
moved to https://github.com/Kong/kubernetes-ingress-controller/pull/1679