docs: release 2.0.5
Kong/kubernetes-ingress-controller pull request #1982
Opened 2021-10-29 17:05 UTC by shaneutt

**What this PR does / why we need it**:

Release 2.0.5

**PR Readiness Checklist**:

- [x] the `CHANGELOG.md` release notes have been updated

2021-10-29 22:21 UTC, rainest requested changes
We may want to try for https://github.com/Kong/kubernetes-ingress-controller/pull/1980 as well since it's basically ready (just needs the go-kong PR and a go-kong release) and the TOC had a typo.

2021-10-29 22:21 UTC, rainest commented on CHANGELOG.md
> + - [2.0.5](#204---20211029)
The anchor was broken and I didn't look at this til after the end of the EDT day, so bumping this to Monday also.
```suggestion
 - [2.0.5](#205---20211101)
```

2021-11-01 13:57 UTC, shaneutt commented
blocked waiting for https://github.com/Kong/kubernetes-ingress-controller/pull/1980

2021-11-02 19:31 UTC, rainest approved these changes

2021-11-02 21:37 UTC, merged