fix: skip logging errors for usage reports
Kong/kubernetes-ingress-controller pull request #2478
Opened 2022-05-10 17:54 UTC by hbagdi

**What this PR does / why we need it**:

When usage reporting calls encounter an error, the code logs an error. 
These errors are not actionable for users and cause unnecessary confusion.
Hence, this patch disables those log statements.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes none

**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [x] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

No changelog entry required.

2022-05-10 18:42 UTC, shaneutt requested changes
Not logging these entries as part of the standard workflow makes sense, because as you say they are not actionable by the end-user. I do however think that absolute silence may not be preferable in all cases. How do you feel about switching these entries to `r.Logger.Debugf` statements instead of completely removing them?

2022-05-10 23:37 UTC, hbagdi commented
> How do you feel about switching these entries to r.Logger.Debugf statements instead of completely removing them?

I personally wouldn't do that.
If a user is switching down to debug-level then it is likely that they are trying to get more details about a problem that they are encountering. If this feature is not working at the same time, it will add to the list of things the user has to think about and rule out. Apart from the maintainers of this project trying to figure out if the feature is working as expected, I don't see any reason to have debug logs.
What do you think?

2022-05-11 13:42 UTC, shaneutt commented
> > How do you feel about switching these entries to r.Logger.Debugf statements instead of completely removing them?
> 
> I personally wouldn't do that. If a user is switching down to debug-level then it is likely that they are trying to get more details about a problem that they are encountering. If this feature is not working at the same time, it will add to the list of things the user has to think about and rule out. Apart from the maintainers of this project trying to figure out if the feature is working as expected, I don't see any reason to have debug logs. What do you think?

I think that if a user was seeing TCP connections going out of their ingress controller but couldn't account for them, it's possible they might turn on debug logging to see if they can better understand what's going on and in that same case they would have a hint about what they would need to change (the reporting flag) to stop those connections from happening.

2022-05-12 20:38 UTC, hbagdi commented
> I think that if a user was seeing TCP connections going out of their ingress controller but couldn't account for them, it's possible they might turn on debug logging to see if they can better understand what's going on and in that same case they would have a hint about what they would need to change (the reporting flag) to stop those connections from happening.

Fair.
The probability of a user doing that is much lower compared to debugging KIC for its behavior.

Let me know if this has to be changed and I'll do it.

2022-05-13 13:22 UTC, shaneutt commented
> > I think that if a user was seeing TCP connections going out of their ingress controller but couldn't account for them, it's possible they might turn on debug logging to see if they can better understand what's going on and in that same case they would have a hint about what they would need to change (the reporting flag) to stop those connections from happening.
> 
> Fair. The probability of a user doing that is much lower compared to debugging KIC for its behavior.
> 
> Let me know if this has to be changed and I'll do it.

If you have the time, yes please. I can make the changes if you prefer.

2022-05-23 22:33 UTC, hbagdi commented
@shaneutt Updated.

2022-05-23 23:54 UTC, shaneutt approved these changes

2022-05-23 23:54 UTC, merged