chore(actions) move build and push image step to be after tests
Kong/kubernetes-ingress-controller pull request #2745
Opened 2022-07-28 03:54 UTC by randmonkey

**What this PR does / why we need it**:

move the build and push image step in nightly and release actions to be after tests, since the building step on `linux/arm64` costs too long.

**Which issue this PR fixes**:

fixes #2744 

**Special notes for your reviewer**:

affects to current actions: if the integration tests fails, the images for nightly build/release may not be pushed.

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [ ] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

2022-07-28 06:04 UTC, randmonkey commented on .github/workflows/release.yaml
> +    needs: verify-manifest-tag
REVIEW: should the integration test step depend on `verify-manifest-tag`?

2022-07-28 16:24 UTC, rainest requested changes
build-push-images runs before tests because the tests in question use that image--the point of these tests is that you have, for example, a manifest that says "use controller image with tag `v1.2.3`" and that manifest does successfully deploy because tag `v1.2.3` does exist and deploys successfully.

You can maybe run the ARM builds after since we're not testing them, but I'm not sure that will work with the multi-arch image system on Docker's side--they may require that you push all of those at once. I'd want to see that building and pushing ARM after does work on a fork/test Docker repo first before merging it here.

That all said, I'd say probably just leave them as-is--the intent of the workflow is that it just starts and probably completes successfully, or it doesn't and alerts you to a failure you need to investigate sometime after. You shouldn't need to wait around for tests to complete as there is no manual step required after them if they succeed, and you have to manually investigate failures regardless no matter how long the process takes.

2022-07-29 03:31 UTC, randmonkey commented
> build-push-images runs before tests because the tests in question use that image--the point of these tests is that you have, for example, a manifest that says "use controller image with tag `v1.2.3`" and that manifest does successfully deploy because tag `v1.2.3` does exist and deploys successfully.
> 
> You can maybe run the ARM builds after since we're not testing them, but I'm not sure that will work with the multi-arch image system on Docker's side--they may require that you push all of those at once. I'd want to see that building and pushing ARM after does work on a fork/test Docker repo first before merging it here.
> 
> That all said, I'd say probably just leave them as-is--the intent of the workflow is that it just starts and probably completes successfully, or it doesn't and alerts you to a failure you need to investigate sometime after. You shouldn't need to wait around for tests to complete as there is no manual step required after them if they succeed, and you have to manually investigate failures regardless no matter how long the process takes.

But currently the test script https://github.com/Kong/kubernetes-ingress-controller/blob/main/hack/e2e/run-tests.sh runs tests in `test/integration` but not `test/e2e`. Maybe I missed some points, but the tests in `test/integration` runs a controller from codebase locally, but not in k8s from a manifest saying "use controller image with tag `v1.2.3`". 

The code for running KIC in integration tests is here: https://github.com/Kong/kubernetes-ingress-controller/blob/24ebeeabf52e138c1b380ca09e1ab4cd904b7976/internal/util/test/controller_manager.go#L79
```go
	// run the controller in the background
	go func() {
		defer os.Remove(kubeconfig.Name())
		fmt.Fprintf(os.Stderr, "INFO: Starting Controller Manager for Cluster %s with Configuration: %+v\n", cluster.Name(), config)
		if err := rootcmd.Run(&config); err != nil {
			panic(err)
		}
	}()
```
We can see we do not depend on the KIC manifests or images in integration tests.

While in recent nightly builds, the build binary step costs 15~20 minutes, which occupied 30%~40% of the total time of the whole action: https://github.com/Kong/kubernetes-ingress-controller/runs/7553013394?check_suite_focus=true 
The longest inner step of the build binary stage is building binary on linux/arm64 platform: 
```
#22 [linux/arm64 builder 9/9] RUN CGO_ENABLED=0 GOOS=linux GOARCH="arm64" GO111MODULE=on go build -a -o manager -ldflags "-s -w -X github.com/kong/kubernetes-ingress-controller/v2/internal/manager/metadata.Release=nightly -X github.com/kong/kubernetes-ingress-controller/v2/internal/manager/metadata.Commit=da51014acde6402b3e3dadd99d466d23d68e6f90 -X github.com/kong/kubernetes-ingress-controller/v2/internal/manager/metadata.Repo=https://github.com/Kong/kubernetes-ingress-controller.git" ./internal/cmd/main.go
#22 DONE 825.6s
```
We cost 825.6s for building binary on arm64 platform, but 144.1s on amd64. So, we could save 10~15 mins on each release of nightly build if we move building binaries and images on arm64 platform to be parallel.

2022-07-29 18:17 UTC, rainest commented
Hmm, yeah, that is running integration tests. It probably shouldn't as there's not much point (they'll already be run on every merge to main, including the one that happens during releases). It looks like we intended to start using the E2E tests at some point and never did: https://github.com/Kong/kubernetes-ingress-controller/blob/a26c2b3be128b2f21343a2cd8c961f9ea7dd5c0c/hack/e2e/run-tests.sh#L3-L7

We should correct that https://github.com/Kong/kubernetes-ingress-controller/issues/2751 (so yes to the first question)

> Is it worth to move the building of images on linux/arm64 to be parallel to save the 10~15 mins in release/nightly build?

IMO it's of limited value for jobs that largely run in the background. Nobody is actively watching the nightly job results; we only care if we get a notification that it failed after completion. Release it informs you if there's a failure earlier, but ideally there just isn't one and you don't care exactly when the tests complete and the job finishes the release.

Since we do want to switch over to E2E tests run against images, that change _would_ need to handle the x86_64 and ARM builds in separate workflow steps, so we can only do that if you can push the architectures of a multi-arch image separately.

2022-07-30 00:53 UTC, closed without merging