chore(ci) omit tests from license scan
Kong/kubernetes-ingress-controller pull request #2764
Opened 2022-08-02 21:51 UTC by rainest

**What this PR does / why we need it**:
Removes the `test` directory before initiating the license scan, to omit test-only dependencies from license reports.

We include our application and its tests in the same repo. The tests aren't compiled into any release artifacts, so it doesn't make sense to include them in the license report we ship with those artifacts. They're also the source of a fair number of license issue reports that we need to investigate and ignore.

Per FOSSA, there's no Go-specific functionality to ignore certain build tags, but deleting those files has the same effect, and we conveniently have those under the same directory (not units, but they're not usually the source of spurious reports because they usually don't add dependencies their package didn't already have).

See [test.txt](https://github.com/Kong/kubernetes-ingress-controller/files/9245901/test.txt) for a POC example with some extra `ls` calls thrown into the job.

2022-08-02 22:39 UTC, shaneutt submitted a review, later dismissed

2022-08-02 22:40 UTC, shaneutt commented on .github/workflows/license.yaml
> +      - shell: bash
I realize, we should add a comment around this to explain.

2022-08-03 17:28 UTC, mflendrich requested changes
I am not convinced that "not included in the artifact we ship" is a strong enough premise to imply that it would render a license we include not worth looking at.

Hypothetically there might be licenses that have unexpected implications even if not compiled directly into the artifact, but just included in the repo. I don't have an immediate answer whether we're likely to come across/include something with such a license, though.

I don't think that we should be making this change.

2022-08-03 17:46 UTC, rainest commented
Added `go mod tidy` as well and had to rearrange some stuff outside of test that linked to test (it was a package that was only used by stuff under `/test`, I think we had it elsewhere because we didn't have an `internal` directory under `test/` earlier).

This breaks in act for some reason, so https://github.com/rainest/kubernetes-ingress-controller/runs/7657773046?check_suite_focus=true

2023-01-17 21:55 UTC, closed without merging

2023-01-17 21:56 UTC, rainest commented
Closed pending feedback from legal.