Add new upstream fields
Kong/kubernetes-ingress-controller pull request #2822
Opened 2022-08-15 23:40 UTC by rainest

**What this PR does / why we need it**:

Adds new 3.x upstream fields to KongIngress.

**Which issue this PR fixes**:

Fix #2812 

**Special notes for your reviewer**:

Depends on a new deck release that includes https://github.com/Kong/deck/pull/735

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [ ] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

2022-08-16 08:45 UTC, randmonkey requested changes

2022-08-16 08:45 UTC, randmonkey commented on pkg/apis/configuration/v1/kongingress_types.go
> +	// Accepted values are: "none", "consumer", "ip", "header", "cookie", "path", "query_arg", "uri_capture".
I did not see `path` in accepted value of `hash_on` here in 3.0 docs preview: https://deploy-preview-4150--kongdocs.netlify.app/gateway/latest/admin-api/#upstream-object. Did I miss anything?

2022-08-16 08:49 UTC, randmonkey approved these changes

2022-08-22 17:52 UTC, rainest commented
Rebased to current main, which uses deck v1.14.0, and added changelog entry; should be all set.

2022-08-22 18:09 UTC, pmalek approved these changes

2022-08-22 18:22 UTC, merged