feat(gateway-api): add destination port matching GEP-957
Kong/kubernetes-ingress-controller pull request #3129
Opened 2022-11-04 17:56 UTC by pmalek

**What this PR does / why we need it**:

This PR aims to implement [GEP-957: Destination Port Matching](https://gateway-api.sigs.k8s.io/geps/gep-957/)

**Which issue this PR fixes**:

Fixes #2709 

**Special notes for your reviewer**:

For now, the routes that will end up not being attached to a Gateway because of unmet port criteria (missing listener in the Gateway with the specified `Port`) will get an `Accepted` condition with `NoMatchingListenerHostname` reason.

This should be addressed also in this PR IMHO and the proposed course of action is:

- use a `const` defined in our codebase
- submit an issue with the above described proposal to https://github.com/kubernetes-sigs/gateway-api/
- swap the self defined `const` with the one defined in upstream whenever (if) it gets released there.

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [ ] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

2022-11-05 00:00 UTC, rainest requested changes
Deleting from the store is the same thing https://github.com/Kong/kubernetes-ingress-controller/pull/3119 does, with the same caveat as its notes. It's a break from what we've been doing, but I think it is probably what we should be doing.

One issue with test logging and testify not providing the tools we need to report issues concisely. Implementation looks fine.

2022-11-05 12:07 UTC, pmalek commented on internal/dataplane/parser/parser.go
> +			// where it's actually in place?
Created #3133 to track this.

2022-11-07 12:40 UTC, pmalek commented on test/integration/utils_test.go
> +		t.Logf("WARNING: http request failed for GET %s/%s: status code %v", proxyURL, path, resp.StatusCode)
Got it. Decided to remove this change from this PR and if I get around to it, handle it in a separate PR.

2022-11-07 19:39 UTC, rainest approved these changes
> Open question: since only HTTPRoute was graduated in beta would it be fine to add tests just for that route type and leave the other ones without (while tracking that in a separate issue: to add whenever they graduate to beta)?

In general, since we do have implementations of the other route types and do test with our alpha flag on, I'd say apply like changes to all unless we expect something to change (if there's an existing GEP or an area of the spec we know is incomplete). Here we should have reasonable confidence that the other route types can (or always will) have ports and will bind to Listeners with those ports, so we could proceed with adding the rest of these immediately.

2022-11-07 19:49 UTC, merged

2022-11-07 21:07 UTC, pmalek commented
> > Open question: since only HTTPRoute was graduated in beta would it be fine to add tests just for that route type and leave the other ones without (while tracking that in a separate issue: to add whenever they graduate to beta)?
> 
> In general, since we do have implementations of the other route types and do test with our alpha flag on, I'd say apply like changes to all unless we expect something to change (if there's an existing GEP or an area of the spec we know is incomplete). Here we should have reasonable confidence that the other route types can (or always will) have ports and will bind to Listeners with those ports, so we could proceed with adding the rest of these immediately.

Good, in such case I'll leave #2709 open for that purpose.