fix(ci): don't use gotestsum in integration tests
Kong/kubernetes-ingress-controller pull request #3748
Opened 2023-03-16 17:25 UTC by pmalek

**What this PR does / why we need it**:

This PR aims to solve a rather convoluted issue with using `-json` when used in `go test`.

https://github.com/golang/go/commit/295516813efb84589a2417178741f31cbb050298#diff-b3e6126779b5ec9d3d6cea7cc54054ba78f4d7a0a6248d9e458bbd9b3d72fce3R1828 (from this CR: https://go-review.googlesource.com/c/go/+/443596) introduced a write to `os.Stderr` when using `-json` with `go test` (which is what `gotestsum` uses).

That creates a (rather rare) data race with https://github.com/Kong/go-kong/blob/c71247b5c8aae2a0afe76da4dcfaf48a17f10bd5/kong/client.go#L182.

This PR aims to fix that by not using `gotestsum` in integration tests (which used `standard-verbose` format by default anyway).

Examplar CI run that contains this data race: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/4439161953/jobs/7791273577#step:8:694

```
==================
WARNING: DATA RACE
Write at 0x000006029430 by main goroutine:
  testing.(*M).Run()
      /opt/hostedtoolcache/go/1.20.2/x64/src/testing/testing.go:1854 +0x279
  github.com/kong/kubernetes-ingress-controller/v2/test/integration.TestMain()
      /home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/test/integration/suite_test.go:211 +0x35a4
  main.main()
      _testmain.go:192 +0x33d

Previous read at 0x000006029430 by goroutine 326:
  github.com/kong/go-kong/kong.NewClient()
      /home/runner/go/pkg/mod/github.com/kong/go-kong@v0.38.1/kong/client.go:182 +0x11e4
  github.com/kong/kubernetes-ingress-controller/v2/internal/adminapi.NewKongClientForWorkspace()
      /home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/internal/adminapi/kong.go:25 +0xea
  github.com/kong/kubernetes-ingress-controller/v2/internal/manager.(*Config).adminAPIClients()
      /home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/internal/manager/setup.go:278 +0x3d2
  github.com/kong/kubernetes-ingress-controller/v2/internal/manager.Run()
      /home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/internal/manager/run.go:64 +0xa8c
  github.com/kong/kubernetes-ingress-controller/v2/internal/cmd/rootcmd.RunWithLogger()
      /home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/internal/cmd/rootcmd/run.go:40 +0x472
  github.com/kong/kubernetes-ingress-controller/v2/internal/util/test.DeployControllerManagerForCluster.func1()
      /home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/internal/util/test/controller_manager.go:95 +0x232

Goroutine 326 (running) created at:
  github.com/kong/kubernetes-ingress-controller/v2/internal/util/test.DeployControllerManagerForCluster()
      /home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/internal/util/test/controller_manager.go:92 +0xbc9
  github.com/kong/kubernetes-ingress-controller/v2/test/integration.TestMain()
      /home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/test/integration/suite_test.go:165 +0x2c51
  main.main()
      _testmain.go:192 +0x33d
==================
```

Suggestions on how we'd like to tackle this differently are more than welcome.

---

Related: #3754

2023-03-16 18:14 UTC, czeslavo commented
https://github.com/Kong/kubernetes-ingress-controller/issues/3567 was reporting this kind of race condition so we should resolve it once the solution is found.

2023-03-16 18:33 UTC, pmalek commented
> 

I knew I was missing something. I don't have an immediate solution for this unfortunately. 

The issue that you linked seemed to be a different one though: it treats about wrong data race attribution to tests. Not about using `-json` (within `gotestsum`) and reading `os.Stderr` in test code. That would be a toolchain issue, rather than `gotestsum`'s, since the problem is in the write at https://github.com/TroutSoftware/go/blob/6a3e0190aed02e038f2efc4d16bf432a0d5be76d/src/testing/testing.go#L1854

😭

2023-03-17 11:16 UTC, pmalek commented
@czeslavo I figured we can use something like https://github.com/jstemmer/go-junit-report.

I added that for integration tests but I left `gotestsum` for e2e for now: so that folks can specify the gotestsum format and get a more succinct test report. PTAL

2023-03-17 12:26 UTC, czeslavo approved these changes
LGTM 👍 Can you please create an issue to track bringing `gotestsum` when the upstream issues are resolved?

2023-03-17 12:27 UTC, czeslavo commented on .github/workflows/_unit_tests.yaml
> +          JUNIT_REPORT: unit-tests.xml
```suggestion
          GOTESTSUM_JUNITFILE: unit-tests.xml
```

2023-03-17 12:28 UTC, czeslavo requested changes
Ah, I noticed that `_unit_tests.yaml` has unnecessary change as these were not changed in the Makefile.

2023-03-17 12:55 UTC, pmalek commented
Should be good now, PTAL @czeslavo. Also I've created this https://github.com/Kong/kubernetes-ingress-controller/issues/3754

2023-03-17 14:03 UTC, czeslavo approved these changes

2023-03-17 14:53 UTC, merged