[WIP] feat: implement assignment of priorities to Kong routes from GRPCRoutes
Kong/kubernetes-ingress-controller pull request #4364
Opened 2023-07-18 08:58 UTC by randmonkey

**What this PR does / why we need it**:

Implement assigning priorities to Kong routes translated from `GRPCRoute`.

**Which issue this PR fixes**:

fixes #4250 

**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [ ] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

2023-07-21 19:16 UTC, rainest requested changes
Making a set of complete GRPCRoute objects that obey additional rules about their rule counts (and validating those rules downstream) feels a bit odd. I feel like we may get clearer code if we create new structs that _must_ obey those rules and has dedicated fields for the rule/match indices instead of adding annotations to the copies. Something like

```
type SplitRuleCollection struct {
	source *gatewayv1alpha2.GRPCRout

	rulesByHostname map[string]Rule
}

// Rule matches the structure of GRPRouteRule, but uses a modified Match type,
// so that we can loop over the Match slice and assign priority correctly,
// and then apply the filters and backends to the generated Kong routes.

type MatchForPriority struct {
	Match gatewayv1alpha2.GRPCRouteMatch
	RuleIndex int
	MatchIndex int
}
```

This has a fair amount of additional validation and conversion code that it seems like we could avoid with dedicated types. Dedicated types would also make it obvious when you're dealing with the derived type or not, whereas as-is it's not obvious in the code whether you're looking at a split GRPCRoute or a regular one.

However, doing the above would require refactoring just about everything in the PR, so I don't think I'd request it unless there's broader consensus from other reviewers that reusing the original type makes the code confusing enough to warrant the change.

2023-07-24 03:43 UTC, randmonkey commented on internal/dataplane/parser/translators/grpcroute_atc.go
> +// to assign higher priority for method match with `Exact` match?
https://github.com/kubernetes-sigs/gateway-api/issues/2216 Created an upstream issue to require clarification here. Before the question gets answered, I think it is necessary to preserve a bit for that.

2023-07-24 03:49 UTC, randmonkey commented
> Making a set of complete GRPCRoute objects that obey additional rules about their rule counts (and validating those rules downstream) feels a bit odd. I feel like we may get clearer code if we create new structs that _must_ obey those rules and has dedicated fields for the rule/match indices instead of adding annotations to the copies. Something like
> 
> ```
> type SplitRuleCollection struct {
> 	source *gatewayv1alpha2.GRPCRout
> 
> 	rulesByHostname map[string]Rule
> }
> 
> // Rule matches the structure of GRPRouteRule, but uses a modified Match type,
> // so that we can loop over the Match slice and assign priority correctly,
> // and then apply the filters and backends to the generated Kong routes.
> 
> type MatchForPriority struct {
> 	Match gatewayv1alpha2.GRPCRouteMatch
> 	RuleIndex int
> 	MatchIndex int
> }
> ```
> 
> This has a fair amount of additional validation and conversion code that it seems like we could avoid with dedicated types. Dedicated types would also make it obvious when you're dealing with the derived type or not, whereas as-is it's not obvious in the code whether you're looking at a split GRPCRoute or a regular one.
> 
> However, doing the above would require refactoring just about everything in the PR, so I don't think I'd request it unless there's broader consensus from other reviewers that reusing the original type makes the code confusing enough to warrant the change.

:+1:  I will do a refactor to remove the direct usage of `GRPCRoute` in the split rules. The assigning of priorities to routes from  `HTTPRoute`s had been also implemented in this way, would you please create another issue for refactoring that after this PR merged? @rainest

2023-07-24 10:15 UTC, randmonkey commented on internal/dataplane/parser/translators/grpcroute_atc.go
> +			// TODO: add `StripPath: false` here?
removed the TODO.

2023-07-24 10:15 UTC, randmonkey commented on CHANGELOG.md
> +  [#4364](https://github.com/Kong/kubernetes-ingress-controller/pull/4364)
done.

2023-07-24 10:15 UTC, randmonkey commented on internal/dataplane/parser/translate_grpcroute.go
> +// Because we need to assign different priorities based on the hostname and match in the specification of HTTPRoutes,
done.

2023-07-24 10:16 UTC, randmonkey commented on internal/dataplane/parser/translators/grpcroute_atc.go
> +		// skip if GRPCRoute does not contain the annotation, because this means the GRPCRoute is not a split one.
refactored this.

2023-07-24 10:19 UTC, randmonkey commented on CHANGELOG.md
> +[grpcroute-specification]: https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1alpha2.GRPCRoute
done.

2023-07-25 17:55 UTC, rainest approved these changes

2023-07-25 17:56 UTC, merged