chore(logs): The log format starts with a capital letter in internal/dataplane
Kong/kubernetes-ingress-controller pull request #5065
Opened 2023-11-02 17:05 UTC by pangruoran

**What this PR does / why we need it**:

**Which issue this PR fixes**:

fixes: #3708 
**Special notes for your reviewer**:

This PR more about `internal/dataplane`

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [ ] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

2023-11-02 17:09 UTC, pmalek commented on CHANGELOG.md
> +
```suggestion
```

2023-11-02 17:11 UTC, pangruoran commented on CHANGELOG.md
> +
Thanks!

2023-11-02 17:13 UTC, pangruoran commented
This will be the last PR for this part of the modification. (it will close #3708)
I hope it can be merged before the release of version 3.0.
Thanks

2023-11-02 17:18 UTC, pmalek submitted a review, later dismissed

2023-11-02 17:31 UTC, pangruoran commented
Sorry, I missed a modification. It has been updated.

2023-11-02 17:52 UTC, pmalek approved these changes

2023-11-03 02:47 UTC, randmonkey requested changes
`kubernetes-ingress-controller/test/integration/translation_failures_test.go` should be updated to match the modified translation failure reasons.

2023-11-03 02:47 UTC, randmonkey commented on internal/dataplane/kong_client.go
> +	c.logger.V(util.DebugLevel).Info("Parsing kubernetes objects into data-plane configuration")
https://github.com/Kong/kubernetes-ingress-controller/blob/13da44018b05d518a01f49bc10320f1c4b710871/internal/dataplane/kong_client.go#L185 
Here should be modified.

2023-11-03 03:36 UTC, randmonkey approved these changes

2023-11-03 04:29 UTC, merged