fix(manager): set InitCacheSyncDuration to 5s by default and allow it…
Kong/kubernetes-ingress-controller pull request #5238
Opened 2023-11-27 15:59 UTC by backjo

… to be configured via cli

**What this PR does / why we need it**:

**Which issue this PR fixes**:

Closes #5175 

**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [ ] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

2023-11-27 15:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Kong/kubernetes-ingress-controller?pullRequest=5238) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Kong/kubernetes-ingress-controller?pullRequest=5238) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Kong/kubernetes-ingress-controller?pullRequest=5238) it.</sub>

2023-11-27 21:01 UTC, rainest requested changes
Does this actually need to be configurable, or is fixing the regression sufficient? We'd left it inaccessible originally because we weren't sure if cases where the resource count was large enough where population did exceed 5s were likely in practice.

It's unfortunately not an intuitive setting to understand if you aren't familiar with the implementation internals, so it felt like it'd likely be an obscure knob where nobody knows when/if they should tweak it.

That's not a huge reason to avoid adding it, but if you _have_ encountered a sufficiently large config set to need it and have logs or other indicators that'd show when users need to increase it, that'd be useful for docs.

2023-11-28 07:32 UTC, backjo commented
> Does this actually need to be configurable, or is fixing the regression sufficient? We'd left it inaccessible originally because we weren't sure if cases where the resource count was large enough where population did exceed 5s were likely in practice.
> 
> It's unfortunately not an intuitive setting to understand if you aren't familiar with the implementation internals, so it felt like it'd likely be an obscure knob where nobody knows when/if they should tweak it.
> 
> That's not a huge reason to avoid adding it, but if you _have_ encountered a sufficiently large config set to need it and have logs or other indicators that'd show when users need to increase it, that'd be useful for docs.

Yeah, I decided to add it because from the logs we put in, we felt a little too close for comfort (~4ish seconds) on the time it took for the initial configuration to be loaded - especially given that a partial configuration results in 4XX errors all over the place for us. I totally agree it's a non-intuitive setting if one is unfamiliar with the implementation details - and ideally a fix per #2315 would get rid of the need for it altogether - but given that it's the current lever used to solve the cache sync problem and the latency may vary depending on the size / performance of the cluster it's being run on, I think it makes sense to expose for operators to configure.

2023-11-28 09:57 UTC, czeslavo commented
Added `backport release/2.12.x` to have it ported to the LTS.

2023-11-28 09:59 UTC, czeslavo approved these changes

2023-11-28 13:46 UTC, mlavacca requested changes
Looks good to me, apart from a minor nit.

2023-11-28 13:46 UTC, mlavacca commented on internal/manager/config.go
> +	flagSet.DurationVar(&c.InitCacheSyncDuration, "init-cache-sync-duration", 5*time.Second, `The initial delay to wait for Kubernetes object caches to be synced before the initial configuration`)
I would use a const value instead of a hardcoded value for the default, as it is the approach we have for all the flags.

2023-11-28 15:24 UTC, mlavacca submitted a review, later dismissed

2023-11-28 16:35 UTC, czeslavo submitted a review, later dismissed

2023-11-28 17:47 UTC, rainest commented
Blah, forgot that you can't quite suggest doc changes there from the PR due to the need for `make generate` to copy those elsewhere.

2023-11-29 08:59 UTC, mlavacca approved these changes

2023-11-29 09:14 UTC, czeslavo approved these changes

2023-11-30 17:44 UTC, rainest approved these changes

2023-11-30 17:45 UTC, merged

2024-01-04 14:50 UTC, piotrwielgolaski-tomtom commented
when can we hope to get this in 3.x line? getting partial configuration is very dangerous