fix(controllers) skip routes bound to excluded GWs
Kong/kubernetes-ingress-controller pull request #5642
Opened 2024-02-21 00:36 UTC by rainest

**What this PR does / why we need it**:

In single-Gateway mode, properly skip route parent references for other Gateways when determining whether to include a route.

**Which issue this PR fixes**:

Currently, single-Gateway mode doesn't actually restrict the controller to routes attached to that Gateway. The original work in https://github.com/Kong/kubernetes-ingress-controller/commit/2e22a101c8a962a4bf17eb3ec72f8845c598d320 doesn't actually filter other routes for two reasons:

- Although we change the controller map functions (via filters in `listHTTPRoutesForGateway()` and the like), controllers [actually queue _all_ route objects(https://github.com/Kong/kubernetes-ingress-controller/blob/7b732489a5e1ec80211e7f61a806bb1818401daf/internal/controllers/gateway/httproute_controller.go#L138-L147), not just those attached to matching Gateways, so that we can process deletes for routes whose Gateway no longer matches or who no longer have a matching Gateway as a parent.
- Although the route filter had some code from the earlier commit, it's unclear how it was supposed to actually filter non-matching routes. In practice it would sorta pretend that the assigned Gateway was the parent even when it doesn't

This fix addresses the second item. We don't need to (and arguably can't--I'm pretty sure there's no other way to handle that class of deletes) address both.

**Special notes for your reviewer**:

Integration can't really test this because it doesn't normally filter Gateways. I used 
[multi-gw.diff.txt](https://github.com/Kong/kubernetes-ingress-controller/files/14352276/multi-gw.diff.txt) off 6e1dcfe534c966f88378886b3375957d0d38479e to validate it. https://github.com/Kong/gateway-operator/pull/1480 can test it in operator integration, but that's obviously elsewhere.

I don't think the existing envtest can check this. It's already checking that there's only one _reported_ attached route, which seems wrong. I didn't check the full path, but I think we maybe have an additional filter on reporting causing that?

E2E could check this. IDK if we want to set that up for regression on what I understand as mostly an operator feature. I don't recall when all/if we run operator tests against controller main.

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [ ] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

2024-02-21 03:09 UTC, randmonkey approved these changes

2024-02-21 10:14 UTC, pmalek requested changes
If we're not adding integration/e2e test (as mentioned in the PR description) can we at least at a UT for that?

I realize that it might require some work to set up but IMHO it's worth the effort.

2024-02-21 18:46 UTC, rainest commented
Okay yeah, I got tunnel vision around the end result of the route showing up in config with two actual Gateways, but you can fake the inputs in the util pretty easily.

2024-02-22 08:49 UTC, czeslavo approved these changes

2024-02-22 09:11 UTC, randmonkey approved these changes

2024-02-22 09:33 UTC, pmalek approved these changes

2024-02-22 09:33 UTC, merged

2024-02-28 10:25 UTC, pmalek commented
@mlavacca The rebase PR using the backport bot failed. Do you plan to create it manually?