[WIP] fix(#5658): handle edge cases for tag filtering detection
Kong/kubernetes-ingress-controller pull request #5682
Opened 2024-03-06 08:51 UTC by ichbinfrog

**What this PR does / why we need it**:

This PR makes detecting if tags filtering is enabled more robust. If the admin API is unreachable, the controller will fail fast rather then disabling tags (which can have undesired consequences, e.g removing objects not managed by the controller).

**Which issue this PR fixes**:

fixes #5658

**Special notes for your reviewer**:

I'm not sure how to add e2e tests for this change since it requires simulating a connection failure during initialization both when the admin api supports tags and does not. 

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [x] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

2024-03-06 08:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Kong/kubernetes-ingress-controller?pullRequest=5682) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Kong/kubernetes-ingress-controller?pullRequest=5682) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Kong/kubernetes-ingress-controller?pullRequest=5682) it.</sub>

2024-03-07 21:54 UTC, rainest commented
I think we can probably do this simpler by just removing the tag support check altogether.

The original introduction of that check is [quite old](https://github.com/Kong/kubernetes-ingress-controller/pull/1415), from an era where there were (maybe? even that long ago I don't think we really supported anything prior to gateway 1.0) gateway versions without tag support in the wild.

3.x releases of KIC cut off support for all gateway releases prior to 3.4, so everything we currently support in the controller supports tags. I'll double check to see if there's any other reason to keep this, but I suspect we can just discard it and always enable tag filtering.

2024-03-08 07:02 UTC, ichbinfrog commented
Thanks for looking into it @rainest 🙏 , whilst you double check if the tag check can be completely removed, I'll deploy this test build in our cluster to see if the issue with consumers getting deleted.

2024-03-12 07:55 UTC, ichbinfrog commented
Small update, the patch deployment made the issue disappear from the Kong Ingress Controller in our Kubernetes cluster. I've also taken the liberty to remove code related to checking tags as you suggested

2024-03-12 23:38 UTC, rainest requested changes
Should be good to go, just needs an updated changelog entry that reflects the final change.

2024-03-12 23:38 UTC, rainest commented on CHANGELOG.md
> +  fails fast rather than disabling tags. [#5658](https://github.com/Kong/kubernetes-ingress-controller/issues/5658)
```suggestion
- Remove unnecessary tag support check that could incorrectly delete configuration if the check did not execute properly. [#5658](https://github.com/Kong/kubernetes-ingress-controller/issues/5658)
```

2024-03-12 23:40 UTC, rainest approved these changes

2024-03-12 23:51 UTC, merged