chore(docs) add 3.1.4 changelog to main
Kong/kubernetes-ingress-controller pull request #5945
Opened 2024-04-26 20:52 UTC by rainest

Reverse changelog backport. See https://github.com/Kong/kubernetes-ingress-controller/pull/5920#issuecomment-2079052081

2024-04-26 21:12 UTC, pmalek approved these changes

2024-04-26 21:13 UTC, pmalek commented on CHANGELOG.md
> + Release date: 2024-04-25
Actually this should be 26

```suggestion
 Release date: 2024-04-26
```

2024-04-27 03:42 UTC, randmonkey requested changes
Changelog in `main` and `release/3.1.x` are diverged. `main` includes some changes that are not included (and will not be backported) to `release/3.1.x` and `release/3.1.x` includes some changes (bumping of golang 1.21.9 and some dependencies) that will not happen in `main`. So cannot simply change the `## Unreleased ` to `3.1.3`/`3.1.4` tags.

2024-04-30 03:14 UTC, randmonkey approved these changes

2024-04-30 03:14 UTC, merged