update changelog for release 3.2.4
Kong/kubernetes-ingress-controller pull request #6413
Opened 2024-08-15 06:41 UTC by randmonkey

**What this PR does / why we need it**:

**Which issue this PR fixes**:

**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [ ] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

2024-08-19 12:07 UTC, pmalek requested changes

2024-08-20 03:21 UTC, randmonkey commented on CHANGELOG.md
> +  [#6395](https://github.com/Kong/kubernetes-ingress-controller/pull/6395)
Added changelog entry.

2024-08-20 07:06 UTC, czeslavo approved these changes

2024-08-20 07:57 UTC, pmalek approved these changes
👍 

Let's remember about `main`'s changelog after we release 3.2.4

2024-08-20 08:15 UTC, merged