chore(ci): make PR checks workflow runnable for external contributors
Kong/kubernetes-ingress-controller pull request #6459
Opened 2024-08-28 09:54 UTC by programmer04

**What this PR does / why we need it**:

It's hard to accept PRs from external contributors, e.g.

- https://github.com/Kong/kubernetes-ingress-controller/pull/6450

because some tests need access to secrets. They can't access them due to GH design. This PR implements the approach described in @mheap [blogpost](https://michaelheap.com/access-secrets-from-forks/) to overcome this limitation.

**Which issue this PR fixes**:

Fixes #3745 

**Special notes for your reviewer**:

What about this code?
https://github.com/Kong/kubernetes-ingress-controller/blob/9cf045b772ae32c57aeea096d99508b5b5a972a6/.github/workflows/checks.yaml#L40-L57
Do we still need it?

2024-08-28 10:17 UTC, randmonkey reviewed
How do we control approval of running checks for PRs from forks? Would it automatically run ALL workflows for ALL PRs?

2024-08-28 10:32 UTC, programmer04 commented
I think it works like that @tao12345666333 
- outside contributor pushes code
- CI fails (lack of permission)
- someone from our team carefully reviews code and re-runs CI
- it passes or fails (depends on the code)

For each code change from an outside contributor for a particular PR the whole cycle repeats. 

Could you confirm @mheap?

2024-08-28 10:32 UTC, programmer04 commented on .github/workflows/_e2e_tests.yaml
> +      - name: get user permission
Done

2024-08-28 10:38 UTC, czeslavo requested changes
As I understand, we should modify the root workflow (`checks.yaml`) to use `on.pull_request_target` instead of the `on.pull_request` trigger so that PRs from forks can access secrets. 

We could also drop `should-run-with-secrets` job from `checks.yaml` (as it will become obsolete with this solution in place) and move the user permissions check up there instead of running them separately in every reusable workflow.

2024-08-28 10:58 UTC, czeslavo reviewed
I meant we could remove all the checks like
```yaml
      - name: get user permission
        id: checkAccess
        uses: actions-cool/check-user-permission@v2
        with:
          require: write
          username: ${{ github.triggering_actor }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: check user permission
        if: steps.checkAccess.outputs.require-result == 'false'
        run: |
          echo "${{ github.triggering_actor }} does not have permissions on this repo."
          echo "Current permission level is ${{ steps.checkAccess.outputs.user-permission }}"
          echo "Job originally triggered by ${{ github.actor }}"
          exit 1
```
from reusable workflows (the ones starting with `_` and with `on.workflow_call` trigger). Instead, we could have just one top-level check in `checks.yaml` that would prevent proceeding further without our approval (retriggering the workflow by us with write permissions). This would reduce the repetition and would guard the whole workflow that is triggered for PRs, making the whole solution safer IMO. By having the checks done down in reusable workflows it will be easier to forget about the fact we need to add one if we add any other that uses secrets.

2024-08-28 11:03 UTC, programmer04 commented
Yes, I've done it. This is why I marked it as a draft for a moment again because I overlooked it before requesting a re-review. now it's done

2024-08-28 11:19 UTC, czeslavo commented on .github/workflows/checks.yaml
> +    - check-permission
Nit: `up-to-date` already needs `check-permission` so we could omit that.

2024-08-28 11:33 UTC, czeslavo approved these changes
LGTM now! 🎖️

2024-08-28 12:01 UTC, mheap submitted a review, later dismissed

2024-08-28 12:14 UTC, czeslavo approved these changes

2024-08-28 12:58 UTC, merged

2024-09-12 16:41 UTC, pmalek commented
This seems to break workflows that rely on code changes that generate changes themselves, e.g. version bump changes like https://github.com/Kong/kubernetes-ingress-controller/pull/6472. That PR was supposed to require the CRDs to get regenerated (to get the updated version https://github.com/Kong/kubernetes-ingress-controller/blob/2869b5b319bc7f043a1a823fc28ee739bc2740f3/config/crd/bases/configuration.konghq.com_kongplugins.yaml#L6) yet it didn't because `pull_request_target` executes in base branch context so it didn't detect those changes.

Now all PRs fail (example: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/10833024315/job/30059016588?pr=6505#step:6:43) because we need to regenerate the CRDs with new version of kubernetes-sigs/controller-tools but for some reason even if that's submitted with the PR (https://github.com/Kong/kubernetes-ingress-controller/pull/6508/commits/0dd97a88e859d1214f9c736f0ee878e6ca98ddf8) the CI executes as if the version of kubernetes-sigs/controller-tools wasn't bumped 🤔