fix: no redundant space in header `Location` for `HTTPRoute` with requestRedirect filter
Kong/kubernetes-ingress-controller pull request #6855
Opened 2024-12-17 13:49 UTC by programmer04

**What this PR does / why we need it**:

**Which issue this PR fixes**:

Fixes https://github.com/Kong/kubernetes-ingress-controller/issues/6851

**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [x] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

2024-12-17 14:22 UTC, randmonkey commented
Please check if there is still the whitespace in #6804.

2024-12-17 14:25 UTC, randmonkey requested changes
Hold here to prevent conflict with #6804.

2024-12-17 14:33 UTC, czeslavo reviewed
👍

2024-12-17 14:33 UTC, czeslavo commented on CHANGELOG.md
> +
As we're on the redundant whitespace topic 😄 
```suggestion
  [#6855](https://github.com/Kong/kubernetes-ingress-controller/pull/6855)
```

2024-12-17 14:53 UTC, czeslavo submitted a review, later dismissed

2024-12-17 16:57 UTC, programmer04 commented
Your PR has been merged @randmonkey, I've rebased this and it's ready to merge too

2024-12-17 17:07 UTC, czeslavo approved these changes

2024-12-18 00:02 UTC, randmonkey approved these changes

2024-12-18 00:02 UTC, merged