Add 0.10.0 changelog
Kong/kubernetes-ingress-controller pull request #818
Opened 2020-08-31 23:39 UTC by rainest

**What this PR does / why we need it**:
It's a changelog!

**Special notes for your reviewer**:
- Draft still pending release date and Ingress v1 PR info, but the rest should all be ready. Probably has some minor omissions since the change history is pretty big and not everything was attached to the milestone, but should hit all the major points.
- Didn't cover Knative now "requiring" class information, since I'm fairly sure this wasn't really possible before (I don't think Knative allows you to create them, and discussion with the Knative team appears to confirm this), it was just something we supported in the code.

2020-09-02 14:19 UTC, mflendrich commented
> Didn't cover Knative now "requiring" class information, since I'm fairly sure this wasn't really possible before (I don't think Knative allows you to create them, and discussion with the Knative team appears to confirm this), it was just something we supported in the code.

Should this be understood as
    a) this changes the interface of KIC to users/other systems but I think it's unlikely that someone will hit this, or
    b) this changes an internal detail of KIC that is theoretically impossible to see on KIC's interface, either documented or undocumented

?

If it's a), LGTM.
If it's b), let's not omit that in the changelog because https://www.hyrumslaw.com/ .

2020-09-02 14:22 UTC, mflendrich requested changes
ditto

2020-09-08 22:03 UTC, rainest commented
What was the ditto? It looks like that was intended as a line comment.

Re Knative class, wasn't really sure--per their devs, it's something they really don't expect and don't intend to support, and Knative itself is new enough that such a loose stipulation is enough to push it into "eh, it's quite unlikely that anyone does rely on this", but went and checked since I was in the area.

In practice, our code _would_ accept classless Knative Ingresses; that was a side effect of using the plain Ingress matching behavior for everything. To get one, however, you'd need to write your own Knative implementation or create Knative Ingresses by hand (I think this is possible, but it kinda defeats the purpose of using Knative to begin with, and it'd probably break a bunch of other stuff).

The standard Knative implementation applies a `"networking.knative.dev/ingress.class": "istio.ingress.networking.knative.dev"` annotation if none is provided in the `knative-serving/config-network` ConfigMap: https://github.com/knative/serving/blob/f141b23104f37206005a3304d4d9951ebfa335e0/vendor/knative.dev/networking/pkg/network.go#L250

It's not wholly impossible if we consider our code in isolation, but outside really contrived scenarios it's impossible in practice.

2020-09-14 23:51 UTC, hbagdi commented on CHANGELOG.md
> + - [0.10.0](#0100---someday)
09/15

2020-09-14 23:51 UTC, hbagdi commented on CHANGELOG.md
> +  This change _cannot_ be overriden.
nit, not a blocker: Instead use "This is not configurable."

2020-09-14 23:51 UTC, hbagdi commented on CHANGELOG.md
> +  This change _cannot_ be overriden.
nit, not a blocker: Instead use "This is not configurable."

2020-09-14 23:51 UTC, hbagdi commented on CHANGELOG.md
> +  [#TBD](https://github.com/Kong/kubernetes-ingress-controller/pull/TBD).
Please instead point to the umbrella issue: https://github.com/Kong/kubernetes-ingress-controller/issues/590

2020-09-14 23:51 UTC, hbagdi commented on CHANGELOG.md
> +- Added flags to enable processing of Ingress and KongConsumer resources
I'll highly recommend to organize this is a little differently.
Instead, have a bullet point on "Following new flags have been introduced" and then have a sub-point to document each of the flag that has been introduced in this release.
This helps with having a single document which can tell us when was which configuration and feature introduced.

2020-09-14 23:51 UTC, hbagdi commented
Also please change this to a regular PR from draft.

2020-09-15 17:18 UTC, mflendrich approved these changes

2020-09-15 17:30 UTC, mflendrich approved these changes

2020-09-15 17:35 UTC, mflendrich approved these changes

2020-09-15 17:36 UTC, hbagdi approved these changes

2020-09-15 17:40 UTC, merged